// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_TLs3IuoWFULHKLQRLFsLZ4j7rOFiQ7U',
    appId: '1:371325571942:web:5b58bf69d70f136ca06ea7',
    messagingSenderId: '371325571942',
    projectId: 'projecto-b5146',
    authDomain: 'projecto-b5146.firebaseapp.com',
    storageBucket: 'projecto-b5146.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlbG8HN2tN2aOpzUlfBZfopBMibVI4hpk',
    appId: '1:371325571942:android:9b0a591a212b1ac2a06ea7',
    messagingSenderId: '371325571942',
    projectId: 'projecto-b5146',
    storageBucket: 'projecto-b5146.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxNpIqugST3_Bagd5RJ3lhJ8CYE4b6_S0',
    appId: '1:371325571942:ios:958e8d2973f591dda06ea7',
    messagingSenderId: '371325571942',
    projectId: 'projecto-b5146',
    storageBucket: 'projecto-b5146.appspot.com',
    iosClientId: '371325571942-1rqcctqjo71ickqqukt0ptab5kbcuo0n.apps.googleusercontent.com',
    iosBundleId: 'com.example.projecto',
  );
}
